### ISSUE TITLE
Finance: add thousands separators to token balances module

### ISSUE THREAD

**Issue by izqui** [aragon/aragon-apps#1065]
Quite hard to read at a glance otherwise:

<img width="666" alt="Screen Shot 2020-01-10 at 5 06 08 PM" src="https://user-images.githubusercontent.com/447328/72167498-828edd80-33cb-11ea-8807-52b2879ebd55.png">

**Comment by Evalir** [comment]
This seems to have been fixed already. :)

Finance (on network dao):
![Screen Shot 2020-04-06 at 5.25.33 PM.png](https://images.zenhubusercontent.com/5931bd7e51aa2c3057804854/424c981a-b6e7-41d4-8b2f-a168a089d9a3)

**Comment by sohkai** [comment]
I think that might've been off of the PR fixing this?

It is currently not fixed on production for me:
![Screen Shot 2020-04-07 at 2.19.58 PM.png](https://images.zenhubusercontent.com/569e0df9638e718c996030c9/7aac31d1-92e9-4e3b-af84-c4c4aaa47c3a)

This will require the API from https://github.com/aragon/aragon-ui/pull/728 :).
